<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net48</TargetFrameworks>
    <RootNamespace>HabitAuthExample</RootNamespace>
    <AssemblyName>HabitAuthExample</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
