<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>HabitAuthConsole</RootNamespace>
    <AssemblyName>HabitAuthConsole</AssemblyName>
  </PropertyGroup>
</Project>
